Module4 task1
htmlacademy-react/89110-six-cities-6 pull request #6
Opened 2021-02-19 00:01 UTC by elismountain

Привет! Есть пара вопросов:

2021-02-19 03:36 UTC, phwb commented
ответил в телеграме

2021-02-20 05:30 UTC, phwb requested changes

2021-02-20 05:30 UTC, phwb commented on src/components/main/main.jsx
> +                <li className="locations__item" key={city} onClick={handleCityClick}>
вот тут лучше полагаться не на `innerText`. у тебя же есть `city` тут, используй его

2021-02-20 05:30 UTC, phwb commented on src/components/map/map.jsx
> +    mapRef.current = leaflet.map(`map`, {
блин, это вам в академии эту фигню рассказывают?

в общем так делать не совсем правильно, лучше сделать так:
```jsx
useEffect(() => {
  leaflet.map(mapRef.current, {...})
}, [])

return (
  <div ref={mapRef} />
);
```
в `mapRef.current` будет лежать дом элемент, чтобы посмотреть можешь сделать `console.log(mapRef.current)` в эффекте

если нужно сохранить ссылку на карту, то можно воспользоваться `useState`

2021-02-20 05:30 UTC, phwb commented on src/components/place-card/place-card.jsx
> +const classModifier = {
какие-то проблемы с выравниванием

2021-02-20 05:30 UTC, phwb commented
объяснение про карту посмотри еще в телеграмме

2021-02-21 11:38 UTC, phwb requested changes

2021-02-21 11:38 UTC, phwb commented on src/components/map/map.jsx
> +    mapRef.current = leaflet.map(mapRef.current, {
сохрани в другую переменную,  реф используется для дом элемента

2021-02-21 11:39 UTC, phwb requested changes

2021-02-21 11:39 UTC, phwb commented on src/components/main/main.jsx
> +                <li className="locations__item" key={city} onClick={handleCityClick}>
вот это так и не поправила

2021-02-21 15:16 UTC, elismountain commented on src/components/main/main.jsx
> +                <li className="locations__item" key={city} onClick={handleCityClick}>
Завтра спрошу, я что то не поняла про inner text

2021-02-21 15:52 UTC, phwb commented on src/components/main/main.jsx
> +                <li className="locations__item" key={city} onClick={handleCityClick}>
в функции `handleCityClick`, ты используешь innerText:
```jsx
  const handleCityClick = (evt) => {
  evt.preventDefault();
  setActiveCity(evt.target.innerText);
};
```
хотя можно делать лучше:
```jsx
<li className="locations__item" key={city} onClick={() => setActiveCity(city)}>
```

2021-02-22 10:34 UTC, phwb approved these changes

2021-02-22 10:34 UTC, phwb commented on src/components/main/main.jsx
>    const handleCityClick = (evt) => {
удали

2021-02-22 10:34 UTC, phwb commented on src/components/map/map.jsx
> +import React, {useRef, useEffect, useState} from 'react';
useState не нужен

2021-02-22 10:34 UTC, merged