Module4 task2
htmlacademy-react/89110-six-cities-6 pull request #7
Opened 2021-02-23 02:46 UTC by elismountain

Привет! 
Разбила UseEffect  в карте на две части - пришлось вернуть mapRef вместо const map - валятся ошибки. По второй части задания добавила пропсы в ревью form и подключила все в offer-screen, вроде бы ошибок нет, но посмотри, пжста

2021-02-23 08:17 UTC, phwb requested changes

2021-02-23 08:17 UTC, phwb commented on package.json
> +    "eslint": "^7.18.0",
крышечку убери

2021-02-23 08:17 UTC, phwb commented on src/components/map/map.jsx
> +    mapRef.current = leaflet.map(mapRef.current, {
ну не правильно же, чтобы понять почему, выведи в консоль `mapRef.current` и посмотри что ты туда записываешь до и после инициализации карты:
```jsx
console.log(mapRef.current) // тут будет DOM элемент
mapRef.current = leaflet.map(mapRef.current)
console.log(mapRef.current) // а теперь экземпляр карты
```
то есть совершенно разные вещи

2021-02-23 08:17 UTC, phwb commented on src/components/map/map.jsx
> +    mapRef.current = leaflet.map(mapRef.current, {
вот пример как разделить эффекты:
```jsx
  const {points} = props;
  const [map, setMap] = useState(null);

  // вот тут создаем карту и сохраняем в локальном стейте
  useEffect(() => {
    // создаем карту
    const nextMap = leaflet.map(mapRef.current, {});
    // ...тут делаем всякие полезые штуки
    // и сохраняем в стейте
    setMap(nextMap);
  }, []);

  // а вот тут проверяем если есть карта и точки
  // то добавим точки на карту
  useEffect(() => {
    if (map && points) {
      points.forEach((point) => leaflet.marker(point).addTo(map));
    }
  }, [map, points]);
```
при таком подходе карта будет создана один раз, а точки будут обновляться при необходимости

2021-02-24 03:41 UTC, phwb commented on src/components/map/map.jsx
> +    const icon = (activePoint && (point.id === activePoint.id)) ? activeIcon : simpleIcon;
зачем тут icon? он нигде не используется

2021-02-24 03:41 UTC, phwb commented on src/components/map/map.jsx
> +      console.log(nextMap);
консоль

2021-02-24 03:53 UTC, phwb commented
![image](https://user-images.githubusercontent.com/4672733/108945046-b84d5f00-767d-11eb-8be9-916b3105e9f7.png)

не знаю как у тебя, но у меня eslint ругается

2021-02-24 03:58 UTC, phwb requested changes

2021-02-24 03:58 UTC, phwb commented on src/components/map/map.jsx
> +  }, []);
забыла про зависимости, но в данном случае можно пропустить.

2021-02-24 03:58 UTC, phwb commented on src/components/map/map.jsx
> +      points.forEach((point) => leaflet.marker(point).addTo(map));
ошибка вылетает вот тут. посмотри что приходит у тебя в points, это явно не то что ожидает leafleat

2021-02-24 04:00 UTC, phwb commented
![image](https://user-images.githubusercontent.com/4672733/108945586-a8824a80-767e-11eb-96eb-ecd402141ec7.png)

и пропиши правильные пути в картинках

2021-02-24 16:37 UTC, elismountain commented
> ![image](https://user-images.githubusercontent.com/4672733/108945046-b84d5f00-767d-11eb-8be9-916b3105e9f7.png)
> 
> не знаю как у тебя, но у меня eslint ругается

Нашла причину, нужно было в package.json Написать "eslint": "eslint --ext .jsx --ext .js src/", вместо  "eslint": "eslint src/**/*.js", сразу 300 ошибок выпало ))

2021-02-26 03:42 UTC, phwb requested changes

2021-02-26 03:42 UTC, phwb commented on src/components/map/map.jsx
> +    if (!map) {
проверка не нужна, этот эффект должен отработать всего один раз

2021-02-26 03:42 UTC, phwb commented on src/components/map/map.jsx
> +  }, [points]);
лишняя зависимость

2021-02-26 03:42 UTC, phwb commented on src/components/map/map.jsx
> +      if (points.length) {
двойной if лишний `if (map && points.length)`

2021-02-26 03:42 UTC, phwb commented on src/components/map/map.jsx
> +  useEffect(() => {
третий эффект лишний, все нужно делать во втором

2021-02-26 03:42 UTC, phwb commented on src/components/map/map.jsx
> +      if (points.length) {
примерно как то так 
```jsx
  useEffect(() => {
    if (map && points.length) {
      points.map((point) => {
        const icon = point.offerId === activeMarker
          ? activeIcon
          : defaultIcon;

        leaflet.marker(
            [point.location.latitude, point.location.longitude],
            {icon},
        ).addTo(map);
      });
    }
  }, [points, map]);
```

2021-02-26 03:42 UTC, phwb commented on src/components/map/map.jsx
> +      if (points.length) {
ну и я запустил приложение в `activeMarker` всегда undefined

2021-03-01 02:50 UTC, phwb approved these changes

2021-03-01 02:50 UTC, merged