Module5 task1
htmlacademy-react/89110-six-cities-6 pull request #8
Opened 2021-03-02 00:31 UTC by elismountain

Привет! 
Нужна помощь со списком городов, завалило ошибками, посмотри пжста.  и еще , я установила все зависимости, но в девтулз не вижу редукса.

2021-03-02 02:49 UTC, phwb commented
до:
![image](https://user-images.githubusercontent.com/4672733/109589141-b7a84300-7b2b-11eb-925c-3d6401028518.png)

после:
![image](https://user-images.githubusercontent.com/4672733/109589197-c4c53200-7b2b-11eb-8909-76abf0a6b05a.png)

там еще ошибки есть, но с ними думаю ты справишься

2021-03-02 02:53 UTC, phwb approved these changes

2021-03-02 02:53 UTC, phwb commented on src/components/main/main.jsx
>    const filteredOffers = offers.filter((offer) => offer.city.name === activeCity);
теперь фильтрация должна быть в функции connect

2021-03-02 02:53 UTC, phwb commented on src/components/main/main.jsx
>    const filteredOffers = offers.filter((offer) => offer.city.name === activeCity);
компонент не должен реализовывать ни какой логики, только отображение данных

2021-03-02 02:54 UTC, phwb requested changes
-

2021-03-09 04:06 UTC, phwb requested changes

2021-03-09 04:06 UTC, phwb commented on src/components/cities-list/cities-list.jsx
> +    onChangeCity(evt.target.innerText);
опять тоже самое. не используй `evt.target.innerText`. у тебя же есть все нужные данные:
```jsx
Object.values(Cities).map((city) => (
  <li className="locations__item" key={city} onClick={() => onChangeCity(city)} />
)

```

2021-03-09 04:06 UTC, phwb commented on src/components/cities-list/cities-list.jsx
> +    dispatch(ActionCreator.setCityOffers());
можно было обойтись одним экшеном

2021-03-09 04:06 UTC, phwb commented on src/components/favorites/favorites.jsx
> +    acc[cur.city.name] = acc[cur.city.name] ? [...(acc[cur.city.name]), cur] : [cur];
всю логику по фильтрации (вообще всю логику) выноси в селектор

2021-03-09 04:06 UTC, phwb commented on src/components/main/main.jsx
>    const filteredOffers = offers.filter((offer) => offer.city.name === activeCity);
тут ничего не поменялось

2021-03-10 02:25 UTC, elismountain commented on src/components/cities-list/cities-list.jsx
> +    dispatch(ActionCreator.setCityOffers());
Удалить тут setCityOffers ? Нужноли тогда удалить его в store?

2021-03-10 02:27 UTC, phwb commented on src/components/cities-list/cities-list.jsx
> +    dispatch(ActionCreator.setCityOffers());
ну ты диспатчишь два экшена, что в свою очередь приводит к выполнению двух редьюсеров. хотя можно было это сделать в одном. то есть, если ты удаляешь экшен, то его логику не забудь перенести в первый

2021-03-10 02:31 UTC, elismountain commented on src/components/cities-list/cities-list.jsx
> +    dispatch(ActionCreator.setCityOffers());
ад  
ничего не понимаю :(

2021-03-10 02:34 UTC, phwb commented on src/components/cities-list/cities-list.jsx
> +    dispatch(ActionCreator.setCityOffers());
когда ты диспатчишь этот эшкен `dispatch(ActionCreator.changeCity(city));`, то выполняется этот кусок кода:
![image](https://user-images.githubusercontent.com/4672733/110567128-d84b4b00-8172-11eb-849f-d675817b8de8.png)

потом ты еще раз диспатчишь экшен `dispatch(ActionCreator.setCityOffers());`, выполняется этот кусок кода
![image](https://user-images.githubusercontent.com/4672733/110567233-fc0e9100-8172-11eb-8be5-dba71b062504.png)

обе эти операции можно сделать в одном экшене. то есть выполнять код не два раза, а один

2021-03-11 00:00 UTC, elismountain commented on src/components/cities-list/cities-list.jsx
> +    dispatch(ActionCreator.setCityOffers());
спасибо!

2021-03-15 03:48 UTC, phwb approved these changes
ошибки поправишь уже в будущем, а то и так долго сидишь на одном задании

2021-03-15 03:48 UTC, phwb commented on src/components/offer-screen/offer-screen-container.jsx
> +  const offer = offers.find((item) => item.id === +id);
а что тебе помешало и эту логику унести в селектор?

2021-03-15 03:48 UTC, merged